name: body_strong
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.0.1
  google_fonts: 6.1.0
  imageview360: ^1.3.0
  http: ^1.1.0
  sqflite: ^2.3.2
  path_provider: ^2.1.1
  table_calendar: ^3.0.9
  pedometer: ^4.0.1
  google_maps_flutter: 2.5.3
  shared_preferences: 2.2.2
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
     - assets/26956302.png
     - assets/na-avy-parni-44.jpg
     - assets/iPhone-13-Pro-Max-13.jpg
     - assets/f155a944721ac5b8f6fede66bb972f0e 1.png
     - assets/bodibilder-myshtsy-sportsmen-sportzal-press 1.png
     - assets/bigpicture_ru_adobestock_216484492 1.png
     - assets/imgpreview 3.jpg
     - assets/Icon/free-icon-profile-3135768 1.png
     - assets/Icon/chat (3) 1.png
     - assets/Icon/workout (1) 1.png
     - assets/Icon/free-icon-running-2843700 1.png
     - assets/Icon/free-icon-diet-561611 1.png
     - assets/Icon/home_(2)_2.png
     - assets/aerial-drone-panorama-view-village-located-near-river-hills-fields-godrays-clouds-moldova.jpg
     - assets/pngwing.com.png
     - assets/png-clipart-fitness-fitness.png
     - assets/AeDYoPkHqrL6hO.gif
     - assets/image/30-year-old man with big muscles.jpg
     - assets/image/_Inner and Outer Strength Man Testing the Limits o.jpg
     - assets/image/a female athlete with a tanned.jpg
     - assets/image/a female athlete with a tanned (1).jpg
     - assets/image/a female athlete with a tanned (2).jpg
     - assets/image/a female athlete with a tanned (3).jpg
     - assets/image/a female athlete with a tanned (4).jpg
     - assets/image/a female athlete with a tanned (5).jpg
     - assets/image/a female athlete with a tanned (6).jpg
     - assets/image/a female athlete with a tanned (7).jpg
     - assets/image/a female athlete with a tanned (8).jpg
     - assets/image/a male athlete with a tanned.jpg
     - assets/image/a male athlete with a tanned (1).jpg
     - assets/image/a male athlete with a tanned (2).jpg
     - assets/image/a male athlete with a tanned (3).jpg
     - assets/image/a male athlete with a tanned (4).jpg
     - assets/image/Fitness girl wears sport bra (1).jpg
     - assets/image/Generate an image of a handsome.jpg
     - assets/image/Generate an image of a handsome (1).jpg
     - assets/image/Muscular sweaty heavyweight alpha men with broad a.jpg
     - assets/image/photo of thin muscular woman.jpg
     - assets/image/photo of thin muscular woman (1).jpg
     - assets/image/portrait of a stunningly beautiful male fairy in s.jpg
     - assets/image/real photo a female athlete with a tanned.jpg
     - assets/image/real photo a female athlete with a tanned (1).jpg
     - assets/image/real photo a male athlete with a tanned.jpg
     - assets/image/real photo a male athlete with a tanned (1) (1).jpg
     - assets/image/real photo a male athlete with a tanned (2).jpg
     - assets/image/real photo a male athlete with a tanned (3).jpg
     - assets/image/real photo a male athlete with a tanned (5).jpg
     - assets/image/real photo a male athlete with a tanned (7).jpg
     - assets/image/real photo a male athlete with a tanned (4) (1).jpg
     - assets/image/Strong biceps.jpg
     - assets/image/Two Muscular sweaty heavyweight alpha men with bro.jpg
     - assets/image/Exercises/abs/0ySzRi0HYVHUfU.gif
     - assets/image/Exercises/abs/1K1d3tyB4CYmN3.gif
     - assets/image/Exercises/abs/1N7VvvXAiMpVwJ.gif
     - assets/image/Exercises/abs/1yqvk4LQPvwybt.gif
     - assets/image/Exercises/abs/FdwFEQmRVEXnJK.gif
     - assets/image/Exercises/abs/RZMcbhAcwWoB4b.gif
     - assets/image/Exercises/abs/ZHjbCHkmPqXmAL.gif
     - assets/image/Exercises/back/Шраги со штангой.gif
     - assets/image/Exercises/back/3O1-V8AH2UHq1o.gif
     - assets/image/Exercises/back/103uFv47RSnZxw.gif
     - assets/image/Exercises/back/e7bb3b0ba4911c6abf8a2e05bed03a2e.gif
     - assets/image/Exercises/back/einarmiges_rudern_am_latzug-sitzend.gif
     - assets/image/Exercises/back/hEYc4x5ojEEGqe.gif
     - assets/image/Exercises/back/hintere_schulter_uebungen-butterfly_reverse_kabelzug-liegend.gif
     - assets/image/Exercises/back/hyperextensions_maschine.gif
     - assets/image/Exercises/back/kabelrudern_breit-sitzend.gif
     - assets/image/Exercises/back/kabelrudern_eng-sitzend.gif
     - assets/image/Exercises/back/kh_rudern-obergriff-schraegbank.gif
     - assets/image/Exercises/back/kh_rudern-untergriff-schraegbank.gif
     - assets/image/Exercises/back/klimmzuege_ueben-stehend.gif
     - assets/image/Exercises/back/kurzhantel_rudern_untergriff-schraegbank.gif
     - assets/image/Exercises/back/latissimus_uebungen-rudern_geraet_breiter_untergriff.gif
     - assets/image/Exercises/back/latziehen_enger_griff-seilzug.gif
     - assets/image/Exercises/back/latziehen_zur_brust-einarmig.gif
     - assets/image/Exercises/back/latzug_muskeln-latziehen_eng_zum_nacken.gif
     - assets/image/Exercises/back/latzug_ruecken-latzug_maschine_obergriff.gif
     - assets/image/Exercises/back/latzug_ruecken-latzug_maschine_untergriff.gif
     - assets/image/Exercises/back/latzug_uebungen-latzug_zum_nacken.gif
     - assets/image/Exercises/back/lh_rudern-t_hantel.gif
     - assets/image/Exercises/back/LK9LeXe6oPsvwy.gif
     - assets/image/Exercises/back/nacken_uebungen_fuer_zuhause-kurzhantel_nackenziehen-brustlehne.gif
     - assets/image/Exercises/back/nackenuebungen_bodybuilding-nackenheben_langhantel-multipresse.gif
     - assets/image/Exercises/back/nackenuebungen_bodybuilding-nackenheben_maschine.gif
     - assets/image/Exercises/back/QwoG6klND8PMNf.gif
     - assets/image/Exercises/back/rudern_einarmig-kabelzug.gif
     - assets/image/Exercises/back/rudern_einarmig-maschine.gif
     - assets/image/Exercises/back/rudern_muskeln-rudern_maschine-enger_griff.gif
     - assets/image/Exercises/back/rudern_sitzend-kabelzug-breiter_obergriff.gif
     - assets/image/Exercises/back/t_bar_ruderzug.gif
     - assets/image/Exercises/back/uebungen_unterer_ruecken_im_stehen-kreuzheben_am_geraet.gif
     - assets/image/Exercises/back/vorgebeugtes_langhantelrudern_untergriff-multipresse.gif
     - assets/image/Exercises/back/vorgebeugtes_rudern_einarmig-kurzhantel.gif
     - assets/image/Exercises/back/YbjoVfsloS6I0O.gif
     - assets/image/Exercises/back/Гиперэкстензия на скамье.gif
     - assets/image/Exercises/back/Гиперэкстензия на фитболе.gif
     - assets/image/Exercises/back/Гиперэкстензия.gif
     - assets/image/Exercises/back/Подтягивание обратным хватом.gif
     - assets/image/Exercises/back/Подтягивания обратным хватом в тренажере.gif
     - assets/image/Exercises/back/Подтягивания парралельным хватом.gif
     - assets/image/Exercises/back/Подтягивания прямым хватом в тренажере.gif
     - assets/image/Exercises/back/Подтягивания узким обратным хватом.gif
     - assets/image/Exercises/back/Подтягивания широким хватом.gif
     - assets/image/Exercises/back/Подтягования перекрестные.gif
     - assets/image/Exercises/back/Пуловер со штангой на наклонной скамье.gif
     - assets/image/Exercises/back/Пуловер со штангой.gif
     - assets/image/Exercises/back/Становая тяга.gif
     - assets/image/Exercises/back/Становя тяга с гантелями.gif
     - assets/image/Exercises/back/Тяга блока сверху в кроссовере.gif
     - assets/image/Exercises/back/Тяга блока сверху за головой.gif
     - assets/image/Exercises/back/Тяга блока сверху узким хватом.gif
     - assets/image/Exercises/back/Тяга блока сверху.gif
     - assets/image/Exercises/back/Тяга штанги в наклоне обратным хватом.gif
     - assets/image/Exercises/back/Тяга штанги в наклоне прямым хватом.gif
     - assets/image/Exercises/back/ш.gif
     - assets/image/Exercises/back/Шраги с гантелями сидя.gif
     - assets/image/Exercises/back/Шраги с гантелями.gif
     - assets/image/Exercises/back/Шраги с резинкой.gif
     - assets/Icon/filter.png
     - assets/Json_fiels/Exercises/Abs.json
     - assets/Json_fiels/Exercises/Back.json
     - assets/Icon/icon_telegram.png
     - assets/Icon/icon_whatsapp.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
